### ISSUE TITLE
请问下如何从零开始搭建一个网络靶场，有什么学习资料推荐吗？

### ISSUE THREAD

**Issue by AlanMaxxx** [fengsec/WebLabs#1]
如题。

**Comment by fengsec** [comment]
> 如题。

* 新手可以在Windows下使用[WAMP](https://www.wampserver.com/)或者[PhpStudy](https://www.xp.cn/download.html)来部署基于PHP的漏洞靶场，Linux下搭建LAMP环境同理
* Linux下也可以通过Docker来一键搭建[Vulhub](https://vulhub.org/#/environments/)漏洞靶场
